spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/reactive-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  flyway:
    url: jdbc:postgresql://127.0.0.1:5432/reactive-db
    user: postgres
    password: admin
